### ISSUE TITLE
Image fails to run on Ubuntu Server 21.04

### ISSUE THREAD

**Issue by manisto** [goofball222/murmur#13]
### OS
```
Distributor ID: Ubuntu
Description:    Ubuntu 21.04
Release:        21.04
Codename:       hirsute
```

### Docker
```
Docker version 20.10.10, build b485636
```

### Labels
```
                "org.opencontainers.image.created": "2021-06-17T22:37:49.252Z",
                "org.opencontainers.image.description": "Murmur (Mumble) Server",
                "org.opencontainers.image.licenses": "Apache-2.0",
                "org.opencontainers.image.revision": "2ea7e1759fc0a9bbebca6ba59797837fd81c6283",
                "org.opencontainers.image.source": "https://github.com/goofball222/murmur",
                "org.opencontainers.image.title": "Murmur (Mumble) Server",
                "org.opencontainers.image.url": "https://github.com/goofball222/murmur",
                "org.opencontainers.image.vendor": "The Goofball - goofball222@gmail.com",
                "org.opencontainers.image.version": "1.3.4"
```

### Compose file
```
version: '3'

services:
  murmur:
    image: goofball222/murmur
    container_name: murmur
    ports:
      - 64738:64738/tcp
      - 64738:64738/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./cert:/opt/murmur/cert
      - ./config:/opt/murmur/config
      - ./data:/opt/murmur/data
      - ./log:/opt/murmur/log
    environment:
      - TZ=UTC

```

### How to reproduce
Simply run a `docker-compose up -d` for a `docker-compose.yml` file with the above mentioned contents.

### Expected results
The container starts and continues to run.

### Actual results
The container exits immediately with the following log:

```
standard_init_linux.go:228: exec user process caused: exec format error
```
